spring:
  application:
    name: symphony-lite-api

  datasource:
    url: jdbc:mysql://localhost:3306/symphony
    username: symphony_user
    password: symphony_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
